---
Name: 'timeline-routes'
Before:
  - '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    'timeline-full-list//$Action/$ID/$OtherID/$Version': 'Sunnysideup\Timeline\Pages\TimelinePageController'





